CREATE TABLE SAJET.G_SN_PRINT
(
  WORK_ORDER       VARCHAR2(25 BYTE)                NOT NULL,
  SEAIAL_NUMBER    VARCHAR2(25 BYTE)                NOT NULL,
  LINE_ID          VARCHAR2(25 BYTE), 
  PROCESS_ID       NUMBER,
  TERMINAL_ID      NUMBER,
  CUSTOMER_SN      VARCHAR2(25 BYTE), 
  CARTON_NO        VARCHAR2(25 BYTE), 
  PALLET_NO        VARCHAR2(25 BYTE),                  
  UPDATE_USERID        NUMBER,
  UPDATE_TIME      DATE              DEFAULT SYSDATE
)
TABLESPACE SYSPPRINT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE INDEX SAJET.G_SN_PRINT_IDX ON SAJET.G_SN_PRINT
(WORK_ORDER, SEAIAL_NUMBER, CUSTOMER_SN)
LOGGING
TABLESPACE SYSPPRINTIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.G_SN_PRINT TO SJ;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.G_SN_PRINT TO SYS_USER;