
CREATE TABLE SAJET.SYS_PRINT_LABEL_FILE_PARAM
(
  LF_ID          NUMBER,
  FUNCTION_NAME  VARCHAR2(50 BYTE), 
  PARAM_TYPE     VARCHAR2(50 BYTE),
  PARAM_NAME     VARCHAR2(50 BYTE),
  PARAM_VALUE    VARCHAR2(255 BYTE),
  UPDATE_USERID  NUMBER,
  UPDATE_TIME    DATE                           DEFAULT SYSDATE
)
TABLESPACE SYSBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE INDEX SAJET.SYS_PRINT_LB_PARAM_FC_NAME ON SAJET.SYS_PRINT_LABEL_FILE_PARAM
(FUNCTION_NAME)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAJET.SYS_PRINT_LB_PARAM_TYPE ON SAJET.SYS_PRINT_LABEL_FILE_PARAM
(PARAM_TYPE)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PRINT_LABEL_FILE_PARAM TO SMT;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PRINT_LABEL_FILE_PARAM TO SYS_USER;
