CREATE TABLE SAJET.SYS_PRINT_LABEL_FILE
(
  LABELFILE_ID   NUMBER,
  SKU_NO         VARCHAR2(20 BYTE),
  LABEL_NAME     VARCHAR2(50 BYTE),
  LABEL_FILE     LONG RAW,
  LABEL_PWD      VARCHAR2(20 BYTE),
  UPDATE_USERID  NUMBER,
  UPDATE_TIME    DATE                           DEFAULT SYSDATE,
  ENABLED        VARCHAR2(10 BYTE)              DEFAULT 'Y'
)
TABLESPACE SYSBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX SAJET.SYS_PRINT_LABEL_FILE_SKU_IDX ON SAJET.SYS_PRINT_LABEL_FILE
(SKU_NO)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX SAJET.SYS_PRINT_LABEL_FILE_ID_PK ON SAJET.SYS_PRINT_LABEL_FILE
(LABELFILE_ID)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          24K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PRINT_LABEL_FILE TO SYS_USER;


--SAJET.SYS_COLOR
CREATE TABLE SAJET.SYS_COLOR
(
  COLOR_ID       NUMBER,
  COLOR_NAME     VARCHAR2(20),
  COLOR_SPEC     VARCHAR2(50),
  COLOR_VALUE    VARCHAR2(20),
  COLOR_PICTURE  LONG RAW,                
  UPDATE_USERID  NUMBER,
  UPDATE_TIME    DATE                           DEFAULT SYSDATE,
  ENABLED        VARCHAR2(10 BYTE)              DEFAULT 'Y'
)

TABLESPACE SYSBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE UNIQUE INDEX SAJET.SYS_COLOR_COLOR_ID_IDX ON SAJET.SYS_COLOR
(COLOR_ID)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX SAJET.SYS_COLOR_COLOR_NAME_IDX ON SAJET.SYS_COLOR
(COLOR_NAME)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_COLOR TO SYS_USER;

