
DROP TABLE SAJET.G_SN_WEIGHT CASCADE CONSTRAINTS;

CREATE TABLE SAJET.G_SN_WEIGHT
(
  WORK_ORDER        VARCHAR2(25 BYTE),
  SERIAL_NUMBER     VARCHAR2(25 BYTE),
  MODEL_ID          NUMBER,
  PDLINE_ID         NUMBER,
  STAGE_ID          NUMBER,
  PROCESS_ID        NUMBER,
  TERMINAL_ID       NUMBER,
  SHIFT_ID          NUMBER,
  WEIGHT            NUMBER,
  CURRENT_STATUS    VARCHAR2(25 BYTE),
  UPDATE_USERID     NUMBER,
  UPDATE_TIME       DATE                           DEFAULT sysdate
)
TABLESPACE SYSRT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE INDEX SAJET.G_SN_WEIGHT_SN_IDX ON SAJET.G_SN_WEIGHT
(SERIAL_NUMBER)
NOLOGGING
TABLESPACE SYSBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAJET.G_SN_WEIGHT_UPDATE_TIME_IDX ON SAJET.G_SN_WEIGHT
(UPDATE_TIME)
NOLOGGING
TABLESPACE SYSBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAJET.G_SN_WEIGHT_MODEL_IDX ON SAJET.G_SN_WEIGHT
(MODEL_ID)
NOLOGGING
TABLESPACE SYSBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX SAJET.G_SN_WEIGHT_PROCESS_IDX ON SAJET.G_SN_WEIGHT
(PROCESS_ID)
NOLOGGING
TABLESPACE SYSBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX SAJET.G_SN_WEIGHT_WO_IDX ON SAJET.G_SN_WEIGHT
(WORK_ORDER)
NOLOGGING
TABLESPACE SYSBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.G_SN_WEIGHT TO SMT;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.G_SN_WEIGHT TO SYS_USER;
