CREATE TABLE SAJET.SYS_PART_GIFT_BOX_PN
(
  PART_ID        NUMBER,
  SKU_NO         VARCHAR2(20 BYTE),
  GIFT_BOX_PN    VARCHAR2(20 BYTE),
  UPC_NO         VARCHAR2(20 BYTE),
  UPDATE_USERID  NUMBER,
  UPDATE_TIME    DATE                           DEFAULT SYSDATE,
  ENABLED        VARCHAR2(1 BYTE)               DEFAULT 'Y'
)
TABLESPACE SYSBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE INDEX SAJET.SYS_PART_GIFT_BOX_PN_PART_IDX ON SAJET.SYS_PART_GIFT_BOX_PN
(PART_ID)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX SAJET.SYS_PART_GIFT_BOX_PN_SKU_IDX ON SAJET.SYS_PART_GIFT_BOX_PN
(SKU_NO)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PART_GIFT_BOX_PN TO SMT;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PART_GIFT_BOX_PN TO SYS_USER;
