CREATE TABLE SAJET.SYS_PART_WEIGHT_PARAM
(
  PART_ID        NUMBER,
  SKU_NO         VARCHAR2(20 BYTE),
  UP_LIMIT       NUMBER                         DEFAULT 0,
  LOW_LIMIT      NUMBER                         DEFAULT 0,
  WAIT_TIME      NUMBER                         DEFAULT 0,
  WEIGHT_COUNT   NUMBER                         DEFAULT 0,
  UPDATE_USERID  NUMBER,
  UPDATE_TIME    DATE                           DEFAULT SYSDATE,
  ENABLED        VARCHAR2(1 BYTE)               DEFAULT 'Y'
)
TABLESPACE SYSBS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE INDEX SAJET.SYS_PART_WEIGHT_PARAM_PART_IDX ON SAJET.SYS_PART_WEIGHT_PARAM
(PART_ID)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX SAJET.SYS_PART_WEIGHT_PARAM_SKU_IDX ON SAJET.SYS_PART_WEIGHT_PARAM
(SKU_NO)
LOGGING
TABLESPACE SYSBSIDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          48K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PART_WEIGHT_PARAM TO SMT;

GRANT DELETE, INSERT, SELECT, UPDATE ON SAJET.SYS_PART_WEIGHT_PARAM TO SYS_USER;
